export const data = [
   {
      id: 1,
      full_name: "Ilyse Pickover",
      email: "ipickover0@wix.com",
      gender: "Female",
      qoutes: "libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum",
   },
   {
      id: 2,
      full_name: "Benedetta Ambrozik",
      email: "bambrozik1@purevolume.com",
      gender: "Female",
      qoutes: "dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis sapien cum sociis natoque penatibus et magnis dis",
   },
   { id: 3, full_name: "Cordell Mowatt", email: "cmowatt2@privacy.gov.au", gender: "Male", qoutes: "justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit" },
   {
      id: 4,
      full_name: "Christye Bernaciak",
      email: "cbernaciak3@digg.com",
      gender: "Female",
      qoutes: "quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus et ultrices",
   },
   { id: 5, full_name: "Kipp Pevreal", email: "kpevreal4@is.gd", gender: "Female", qoutes: "nulla nunc purus phasellus in felis donec semper sapien a libero" },
   {
      id: 6,
      full_name: "Nettie Jennison",
      email: "njennison5@cnbc.com",
      gender: "Female",
      qoutes: "et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis",
   },
   {
      id: 7,
      full_name: "Robby Goodchild",
      email: "rgoodchild6@ehow.com",
      gender: "Female",
      qoutes: "malesuada in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum dolor sit amet consectetuer",
   },
   {
      id: 8,
      full_name: "Luca McConnel",
      email: "lmcconnel7@utexas.edu",
      gender: "Male",
      qoutes: "nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros elementum pellentesque quisque",
   },
   {
      id: 9,
      full_name: "Garrott Laffling",
      email: "glaffling8@360.cn",
      gender: "Male",
      qoutes: "fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh",
   },
   { id: 10, full_name: "Bartholomeus Ollerearnshaw", email: "bollerearnshaw9@quantcast.com", gender: "Male", qoutes: "arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque" },
];
